### ISSUE TITLE
urn notation not supported?

### ISSUE THREAD

**Issue by stevage** [perliedman/reproject#19]
I come across GeoJSON files with CRS sections like this:

```
"crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:EPSG::28354"
    }
  }
```

but if I call reproject like this:

```
reproject.detectCrs(geojson, { "EPSG:28354": "+proj=utm +zone=54 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs" } );
```

it fails, because the simple text lookup doesn't work. 

The 2008 GeoJSON spec definitely recommends the URN format: http://geojson.org/geojson-spec.html#named-crs

Am I missing something?

**Comment by perliedman** [comment]
The identification is done simply [by name](https://github.com/perliedman/reproject/blob/master/index.js#L55), so if the GeoJSON's CRS `name` is `urn:ogc:def:crs:EPSG::28354`, you would have to put exactly that name in your definition dictionary:

```
{ "urn:ogc:def:crs:EPSG::28354": "+proj=utm +zone=54 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs" }
``` 
So, `name` actually has to be the name!

**Comment by stevage** [comment]
Yes, I could see that. I'm just puzzled by that choice - and the fact that the sample defs file doesn't match the recommended standard.

Why not just include a (near-)comprehensive list of definitions? [Here's what I ended up doing](https://github.com/stevage/epsg/blob/master/index.js).

(Maybe I don't entirely understand the use case of this library. I was expecting to be able to throw any GeoJSON file at it, and reproject to EPSG:4326. Having to work out the projection of each source file, track down the definition, and add that to a file seemed to defeat a lot of the point...)

**Comment by perliedman** [comment]
I've typically used the project in cases where I already know the projection, I don't remember if I actually used the detection logic myself. That is, I've used the lib for the actual reprojection rather than detection.

My thinking is that if GeoJSON thinks it's necessary to be as explicit as the `urn` format is, then the dictionary should need to be as explicit as well - there's no need for the `urn` part if the dictionary will assume everything is EPSG anyway.

Regarding examples, I guess you could say I'm sloppy. My own thinking is that the whole `urn` idea is over engineered, so I ignored it for my examples, although it's a recommendation.

For the current version of GeoJSON, there's no official support for projections other than WGS84, so I guess we're free to use any identifier and forget about the 2008 recommendations. For this case, the current approach works well, since you can use any name you like, again including the `urn` if that is preferred.

I'm open for suggestions on improving this situation, but I'm not likely to do much work on it myself!

**Comment by stevage** [comment]
Ok, my suggestion is to add a couple of lines of guidance which would solve people with my use case (reproject GeoJSON files of unknown, but common, projections specified using either raw EPSG or URN notation). See PR.
