### ISSUE TITLE
Defective output since 1.2.0

### ISSUE THREAD

**Issue by stevage** [perliedman/reproject#34]
Not sure if I'm doing something wrong, but I'm getting output that is not valid GeoJSON (or valid JSON at all for that matter)

```
reproject --from=EPSG:3111 --to=EPSG:4326 --crs-defs=crs-defs.json > out.json
```

Here's my minimal input file:

```
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type": "Point",
                "coordinates": [
                    2491040.896494411,
                    2446883.374888715
                ]
            }
        }
    ]
}
```

The output:

```
{
  "type": "FeatureCollection"
}
{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Point",
    "coordinates": [
      144.89869880923632,
      -37.4786293486176
    ]
  }
}
```

That is, a FeatureCollection object, followed by a series of Feature objects, with newlines between them.

I just went back and checked against old versions. In version 1.1.1 this worked fine, then it broke in 1.2.0.

Also, I didn't include this in the sample above, but 1.2.0 doesn't reproject the coordinates of the bbox property if there is one.

**Comment by perliedman** [comment]
Interesting. This is because I apparently haven't tested `FeatureCollection`s through the CLI after the switch to use `geojson-stream`.

I can reproduce the issue and even fix it, but that instead broke single geometries, so I will have to look into how to handle `FeatureCollection`s as well as the simpler objects; work in progress here: https://github.com/perliedman/reproject/tree/fix-streaming-featurecollections - any help is of course more than welcome.

**Comment by perliedman** [comment]
@stevage I've pushed what I believe is a fix to the branch above; if you can find the time, feel free to try it out to see if it works as you expect. If you don't have the time/energy, no worries, I'll merge in a couple of days and hope for the best!

**Comment by stevage** [comment]
Thanks, that's awesome. I have dropped it into the pipeline where it failed previously, and can confirm that it produced the right result this time around. Not exactly exhaustive testing, admittedly.
